defaults:
  - _self_
  - override hydra/job_logging: disabled
hydra:
  output_subdir: null
  run:
    dir: logs/hydra
main:
  experiment_name_prefix: VAE_vgg_VAE_vgg_9_11_20_3_35_resumed
  seed: 42
  num_workers: 0
  parallel: True
  gpus_to_use: 1,2,3,4,5,6
  trains: False
  train_size: 0.8
  auto_encoder_latent_dim: 512
  paths:
    train:
      path: './data/images/croppedhdf5_files'
      number_of_samples: 63000
    validation: 'data/validation.pkl'
    logs: 'logs/'
train:
  num_epochs: 500
  grad_clip: 0.25
  dropout: 0.3
  num_hid: 20
  batch_size: 64
  save_model: True
  GaussianNLLLoss_var: 0.1
  lr:
    lr_value: 1e-5
    lr_decay: 15
    lr_gamma: 0.3
    lr_step_size: 50